"use client";
import { useState } from "react";
type Address={id:string;province:string;district:string;sector:string;cell:string|null;village:string|null;details:string|null};
type Order={id:string;total:any;status:string;createdAt:string|Date;payment:{status:string;method:string}|null;items:{id:string;quantity:number;unitPrice:any;product:{name:string;slug:string;images:{url:string}[]}}[]};
const stages=["PENDING","PAID","PROCESSING","SHIPPED","DELIVERED"];
function stageIndex(status:string){const i=stages.indexOf(status);return i<0?0:i}
export default function AccountClient({initialUser,initialAddresses,initialOrders}:{initialUser:{name:string|null;email:string|null;phone:string|null;createdAt:Date};initialAddresses:Address[];initialOrders:Order[]}){
 const [tab,setTab]=useState("profile"); const [user,setUser]=useState(initialUser); const [addresses,setAddresses]=useState(initialAddresses); const [orders]=useState(initialOrders);
 const [message,setMessage]=useState("");
 async function saveProfile(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(user)});const d=await r.json();setMessage(r.ok?"Profile updated.":d.error||"Could not update profile.");if(r.ok)setUser(d.user);}
 async function addAddress(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const r=await fetch("/api/addresses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.ok){setAddresses(a=>[d.address,...a]);e.currentTarget.reset();setMessage("Address saved.");}else setMessage(d.error||"Could not save address.");}
 async function removeAddress(id:string){const r=await fetch("/api/addresses",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});if(r.ok)setAddresses(a=>a.filter(x=>x.id!==id));}
 return <main className="accountPage"><div className="accountHeader"><div><div className="eyebrow">MY ACCOUNT</div><h1>Hello, {user.name||"Customer"}</h1><p>Manage your profile, addresses, orders and delivery tracking.</p></div><a href="/products" className="cta">Continue shopping</a></div>
 <div className="accountTabs">{[["profile","Profile"],["addresses","Addresses"],["orders","My Orders"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {message&&<div className="sellerMessage">{message}</div>}
 {tab==="profile"&&<section className="accountCard"><h2>Profile</h2><form onSubmit={saveProfile}><label>Full name<input value={user.name||""} onChange={e=>setUser({...user,name:e.target.value})}/></label><label>Email<input type="email" value={user.email||""} onChange={e=>setUser({...user,email:e.target.value})}/></label><label>Phone<input value={user.phone||""} onChange={e=>setUser({...user,phone:e.target.value})}/></label><button className="cta">Save profile</button></form></section>}
 {tab==="addresses"&&<section className="accountGrid"><div className="accountCard"><h2>Add address</h2><form onSubmit={addAddress}><label>Province<input name="province" placeholder="Kigali City" required/></label><label>District<input name="district" placeholder="Gasabo" required/></label><label>Sector<input name="sector" placeholder="Remera" required/></label><label>Cell<input name="cell" placeholder="Optional"/></label><label>Village<input name="village" placeholder="Optional"/></label><label>Delivery details<textarea name="details" placeholder="Street, house number, landmark..."/></label><button className="cta">Save address</button></form></div><div className="accountCard"><h2>Your addresses</h2>{addresses.map(a=><div className="addressItem" key={a.id}><strong>{a.province} · {a.district} · {a.sector}</strong><span>{[a.cell,a.village,a.details].filter(Boolean).join(" · ")}</span><button onClick={()=>removeAddress(a.id)}>Remove</button></div>)}{!addresses.length&&<p>No saved addresses yet.</p>}</div></section>}
 {tab==="orders"&&<section className="accountOrders"><h2>My Orders</h2>{orders.map(o=>{const current=stageIndex(o.status);return <article className="orderCard" key={o.id}><div className="orderCardTop"><div><strong>Order #{o.id.slice(-8).toUpperCase()}</strong><span>{new Date(o.createdAt).toLocaleString()}</span></div><strong>RWF {Number(o.total).toLocaleString()}</strong></div><div className="tracking"><div className="trackingLine"/>{stages.map((s,i)=><div className={"trackingStep "+(i<=current&&o.status!=="CANCELLED"?"done":"")} key={s}><span>{i+1}</span><small>{s==="PENDING"?"Order placed":s==="PAID"?"Payment confirmed":s[0]+s.slice(1).toLowerCase()}</small></div>)}</div><div className="orderItems">{o.items.map(i=><div key={i.id}><span>{i.product.name} × {i.quantity}</span><strong>RWF {(Number(i.quantity)*Number(i.unitPrice)).toLocaleString()}</strong></div>)}</div><a className="secondaryButton" href={"/orders/"+o.id}>View order details</a></article>})}{!orders.length&&<div className="accountCard"><p>You have no orders yet.</p><a href="/products" className="cta">Start shopping</a></div>}</section>}
 </main>
}
