import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";
export default async function AdminPaymentsPage(){
 const session=await requireAuth(["ADMIN"]).catch(()=>null);if(!session)redirect("/login?next=/admin/payments");
 const orders=await prisma.order.findMany({include:{user:{select:{name:true,email:true,phone:true}}},orderBy:{createdAt:"desc"},take:200});
 return <main className="portal"><AdminSidebar active="Payments"/><section className="portalMain"><div className="portalTop"><div><div className="eyebrow">ADMIN PORTAL</div><h1>Payments</h1><p className="portalSub">Order payment records currently tracked by AkaziConnect.</p></div></div><div className="panel"><div className="adminTableWrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Payment state</th><th>Date</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>#{o.id.slice(-8).toUpperCase()}</strong></td><td>{o.user.name||o.user.phone||o.user.email||"Customer"}</td><td>{Number(o.total).toLocaleString()} FRW</td><td><span className={"statusPill status-"+o.status.toLowerCase()}>{o.status==="PAID"||o.status==="PROCESSING"||o.status==="SHIPPED"||o.status==="DELIVERED"?"PAID":o.status==="CANCELLED"||o.status==="REFUNDED"?"FAILED / REFUNDED":"PENDING"}</span></td><td>{o.createdAt.toLocaleString("en-GB")}</td></tr>)}</tbody></table>{!orders.length&&<div className="emptyState">No payment records found.</div>}</div></div></section></main>;
}
function AdminSidebar({active}:{active:string}){const links=[["Overview","/admin"],["Customers","/admin/customers"],["Sellers","/admin/sellers"],["Products","/admin/products"],["Orders","/admin/orders"],["Payments","/admin/payments"],["Categories","/admin/categories"]];return <aside className="portalSide"><div className="brand"><span className="brandMark">A</span>AkaziConnect</div><h3>Admin Portal</h3>{links.map(([l,h])=><a key={l} href={h} className={active===l?"portalNavActive":""}>{l}</a>)}</aside>;}
